<% project_name = 'commoncritic' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: commoncritic_development

test:
  <<: *default
  database: commoncritic_test
